insert into public.patients (
  id,
  user_id,
  first_name,
  last_name,
  email,
  phone,
  date_of_birth,
  gender,
  blood_type,
  address,
  allergies,
  medical_history,
  insurance_id,
  emergency_contact_name,
  emergency_contact_phone,
  emergency_contact_relationship,
  created_by,
  created_at,
  updated_at
) values
  (
    gen_random_uuid(),
    null,
    'Ama',
    'Mensah',
    'ama.mensah@example.com',
    '+233200000001',
    '1992-03-15',
    'female',
    'O+',
    'Accra, Ghana',
    array['Pollen'],
    '{"conditions":["Asthma"],"notes":"Uses inhaler as needed"}'::jsonb,
    'INS-1001',
    'Kofi Mensah',
    '+233200000002',
    'Spouse',
    null,
    now(),
    now()
  ),
  (
    gen_random_uuid(),
    null,
    'Yaw',
    'Boateng',
    'yaw.boateng@example.com',
    '+233200000003',
    '1985-08-02',
    'male',
    'A-',
    'Kumasi, Ghana',
    array['Penicillin'],
    '{"conditions":["Hypertension"],"notes":"Monitoring blood pressure"}'::jsonb,
    'INS-1002',
    'Akosua Boateng',
    '+233200000004',
    'Sister',
    null,
    now(),
    now()
  ),
  (
    gen_random_uuid(),
    null,
    'Esi',
    'Owusu',
    'esi.owusu@example.com',
    '+233200000005',
    '1998-11-21',
    'female',
    'B+',
    'Cape Coast, Ghana',
    null,
    '{"conditions":[],"notes":"No chronic conditions"}'::jsonb,
    null,
    'Kojo Owusu',
    '+233200000006',
    'Father',
    null,
    now(),
    now()
  );
